module.exports.prompts = [
  'Is it better to read books in electronic form or actually hold the book?',
  "What's your biggest first world problem?",
  'What do you wish you had more talent doing?',
  "What's your current biggest worry?",
  'What one thing would significantly make your life better?',
  "What's the worst piece of advice you ever got from someone?",
  'If everyone was a color, what color would you be?',
  'What have you recently felt grateful for?',
  'What recent event have you seen that restored your faith in humankind?',
  "What's something others purchase that you simply can't understand why?",
  'What challenge would you like to see your best friend take on?',
  'What was the last dream you can remember about?',
  'What food do you have a love-hate relationship with?',
];

module.exports.options = [
  'sir',
  'engine',
  'tradition',
  'alcohol',
  'reality',
  'secretary',
  'operation',
  'cell',
  'guidance',
  'guitar',
  'week',
  'woman',
  'contribution',
  'cheek',
  'distribution',
  'climate',
  'user',
  'football',
  'client',
  'addition',
  'exam',
  'mood',
  'instruction',
  'appearance',
  'priority',
  'television',
  'newspaper',
  'assistant',
  'coffee',
  'development',
  'gene',
  'law',
  'chapter',
  'scene',
  'definition',
  'patience',
  'owner',
  'hair',
  'writing',
  'candidate',
  'tooth',
  'university',
  'disease',
  'advice',
  'passion',
  'outcome',
  'accident',
  'obligation',
  'celebration',
  'dirt',
];
